import type { Metadata } from "next";
import { Reddit_Sans_Condensed } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import CircularMenu from "@/components/ui/action-bar";
import { Provider } from "./provider";
import { AnimatedBackground } from "@/components/ui/animated-background";

const redditSansCondensed = Reddit_Sans_Condensed({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-reddit-sans-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redditSansCondensed.variable} antialiased relative`}>
        <AnimatedBackground />
        
        <div className="relative z-10">
          <Provider>{children}</Provider>
        </div>

        {/* Scripts */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-BRSFV6Z670"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BRSFV6Z670');
          `}
        </Script>
        <Script id="zoho-salesiq-script" strategy="afterInteractive">
          {`
            window.$zoho = window.$zoho || {};
            $zoho.salesiq = $zoho.salesiq || { ready: function() {} };
          `}
        </Script>
        <Script
          src="https://salesiq.zohopublic.com/widget?wc=siqa0752c8be10fd2a9c8a8ee410ead149d053833bd70cb502f6d44d629c00581b8"
          strategy="afterInteractive"
        />
        <CircularMenu position="left" />
      </body>
    </html>
  );
}
